name: unitapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  math_keyboard: ^0.2.1
  font_awesome_flutter: ^10.6.0
  flutter_math_fork: ^0.7.1
  flutter_colorpicker: ^1.0.3
  ionicons: ^0.2.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.3
  share_plus: ^7.2.1
  screenshot: ^2.1.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/
    - assets/icon/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700

    - family: Work Sans
      fonts:
        
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
          weight: 900

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon/appLogo.png"
  adaptive_icon_background: "#FFFFFF"

# To add fonts to your application, add a fonts section here, in this "flutter" section.
# For details regarding fonts from package dependencies, see https://flutter.dev/custom-fonts/#from-packages
