// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx4tFDMZGCWhKhG3bgD-KIvS2rp65Krx4',
    appId: '1:659362672663:web:bfc797e755209ca2a0ac52',
    messagingSenderId: '659362672663',
    projectId: 'unitapp-firebase',
    authDomain: 'unitapp-firebase.firebaseapp.com',
    storageBucket: 'unitapp-firebase.appspot.com',
    measurementId: 'G-K0K7Y4HMQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYVi2cj4qyM9sRRVh0vefyd2OES3PiHfM',
    appId: '1:659362672663:android:26d8c658e9af3bada0ac52',
    messagingSenderId: '659362672663',
    projectId: 'unitapp-firebase',
    storageBucket: 'unitapp-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy3ImYUqeLOaUvKHycdNq7W9idCSFW1Eo',
    appId: '1:659362672663:ios:388f703331927a42a0ac52',
    messagingSenderId: '659362672663',
    projectId: 'unitapp-firebase',
    storageBucket: 'unitapp-firebase.appspot.com',
    iosBundleId: 'com.appevolvelabs.unitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy3ImYUqeLOaUvKHycdNq7W9idCSFW1Eo',
    appId: '1:659362672663:ios:32573a14e09d0f49a0ac52',
    messagingSenderId: '659362672663',
    projectId: 'unitapp-firebase',
    storageBucket: 'unitapp-firebase.appspot.com',
    iosBundleId: 'com.example.unitapp.RunnerTests',
  );
}
